<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<AvaloniaNativeAotSingleFile>true</AvaloniaNativeAotSingleFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.0" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.0" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.0">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
		<DirectPInvoke Include="libHarfBuzzSharp" />
		<NativeLibrary Include="lib\win64\libHarfBuzzSharp.lib" />
		<DirectPInvoke Include="libSkiaSharp" />
		<NativeLibrary Include="lib\win64\skia.lib" />
		<NativeLibrary Include="lib\win64\SkiaSharp.lib" />
		<DirectPInvoke Include="av_libglesv2" />
		<NativeLibrary Include="lib\win64\libANGLE_static.lib" />
		<NativeLibrary Include="lib\win64\libGLESv2_static.lib" />
		<NativeLibrary Include="d3d9.lib" />
		<NativeLibrary Include="dxguid.lib" />
		<NativeLibrary Include="dxgi.lib" />
		<NativeLibrary Include="Synchronization.lib" />
		<NativeLibrary Include="user32.lib" />
		<NativeLibrary Include="gdi32.lib" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Views\AdvancedInstallView.axaml.cs">
	    <DependentUpon>AdvancedInstallView.axaml</DependentUpon>
	  </Compile>
	</ItemGroup>
</Project>
